/** One-click looks. Appearance only — never touches your texts, clients or images. */
export const TEMPLATES = [
  {
    id: "dark-premium",
    name: "Dark Premium",
    desc: "Το αρχικό: βαθύ μαύρο, γαλάζιο accent, απαλές λάμψεις.",
    swatch: ["#050505", "#60d6ff", "#ffffff"],
    patch: {
      "theme.mode": "dark",
      "theme.bg": "#050505",
      "theme.surface": "#0a0a0c",
      "theme.accent": "#60d6ff",
      "theme.accentDeep": "#2563eb",
      "theme.accentSoft": "#a8ecff",
      "theme.borderColor": "#ffffff",
      "theme.borderOpacity": 8,
      "theme.cardRadius": 24,
      "theme.grain": true,
      "theme.glows": true,
      "theme.gridLines": true,
      "theme.fonts.display": "Bricolage Grotesque",
      "theme.fonts.body": "Manrope",
      "theme.fonts.headingWeight": 800,
      "theme.buttons.shape": "pill",
      "theme.buttons.primaryBg": "#ffffff",
      "theme.buttons.primaryText": "#000000",
      "theme.buttons.secondaryStyle": "outline",
      "theme.icons.style": "soft",
    },
  },
  {
    id: "minimal-light",
    name: "Minimal Light",
    desc: "Λευκό, καθαρό, editorial. Ιδανικό για premium brands.",
    swatch: ["#f6f6f8", "#2563eb", "#12121a"],
    patch: {
      "theme.mode": "light",
      "theme.ink": "#14141c",
      "theme.bg": "#f6f6f8",
      "theme.surface": "#ffffff",
      "theme.accent": "#2563eb",
      "theme.accentDeep": "#1e3a8a",
      "theme.accentSoft": "#93c5fd",
      "theme.borderColor": "#14141c",
      "theme.borderOpacity": 12,
      "theme.cardRadius": 18,
      "theme.grain": false,
      "theme.glows": false,
      "theme.gridLines": false,
      "theme.fonts.display": "Plus Jakarta Sans",
      "theme.fonts.body": "Inter",
      "theme.fonts.headingWeight": 700,
      "theme.buttons.shape": "rounded",
      "theme.buttons.primaryBg": "#12121a",
      "theme.buttons.primaryText": "#ffffff",
      "theme.buttons.secondaryStyle": "outline",
      "theme.icons.style": "soft",
    },
  },
  {
    id: "neon-night",
    name: "Neon Night",
    desc: "Μωβ/φούξια νέον, cyber αίσθηση, έντονες λάμψεις.",
    swatch: ["#07021a", "#b026ff", "#ff5ae5"],
    patch: {
      "theme.mode": "dark",
      "theme.bg": "#07021a",
      "theme.surface": "#100829",
      "theme.accent": "#b026ff",
      "theme.accentDeep": "#4c1d95",
      "theme.accentSoft": "#ff5ae5",
      "theme.borderColor": "#c084fc",
      "theme.borderOpacity": 14,
      "theme.cardRadius": 10,
      "theme.grain": true,
      "theme.glows": true,
      "theme.gridLines": true,
      "theme.fonts.display": "Space Grotesk",
      "theme.fonts.body": "DM Sans",
      "theme.fonts.headingWeight": 700,
      "theme.buttons.shape": "square",
      "theme.buttons.primaryBg": "#b026ff",
      "theme.buttons.primaryText": "#ffffff",
      "theme.buttons.secondaryStyle": "solid",
      "theme.icons.style": "outline",
    },
  },
  {
    id: "editorial",
    name: "Editorial Gold",
    desc: "Σοβαρό, τυπογραφικό, χρυσές πινελιές.",
    swatch: ["#0c0b09", "#e8c37a", "#f5efe4"],
    patch: {
      "theme.mode": "dark",
      "theme.bg": "#0c0b09",
      "theme.surface": "#15130f",
      "theme.accent": "#e8c37a",
      "theme.accentDeep": "#8a6a2f",
      "theme.accentSoft": "#f6e3bd",
      "theme.borderColor": "#e8c37a",
      "theme.borderOpacity": 10,
      "theme.cardRadius": 4,
      "theme.grain": true,
      "theme.glows": false,
      "theme.gridLines": false,
      "theme.fonts.display": "Playfair Display",
      "theme.fonts.body": "Lora",
      "theme.fonts.headingWeight": 700,
      "theme.buttons.shape": "square",
      "theme.buttons.primaryBg": "#e8c37a",
      "theme.buttons.primaryText": "#140f05",
      "theme.buttons.secondaryStyle": "ghost",
      "theme.icons.style": "plain",
    },
  },
  {
    id: "warm-sunset",
    name: "Warm Sunset",
    desc: "Ζεστά πορτοκαλί, φιλικό και ορεκτικό — τέλειο για food.",
    swatch: ["#140a08", "#ff7a45", "#ffd6a5"],
    patch: {
      "theme.mode": "dark",
      "theme.bg": "#140a08",
      "theme.surface": "#1e100c",
      "theme.accent": "#ff7a45",
      "theme.accentDeep": "#c2410c",
      "theme.accentSoft": "#ffd6a5",
      "theme.borderColor": "#ffb08a",
      "theme.borderOpacity": 10,
      "theme.cardRadius": 28,
      "theme.grain": false,
      "theme.glows": true,
      "theme.gridLines": false,
      "theme.fonts.display": "Outfit",
      "theme.fonts.body": "Figtree",
      "theme.fonts.headingWeight": 800,
      "theme.buttons.shape": "pill",
      "theme.buttons.primaryBg": "#ff7a45",
      "theme.buttons.primaryText": "#1a0b06",
      "theme.buttons.secondaryStyle": "solid",
      "theme.icons.style": "soft",
    },
  },
  {
    id: "mono-brutal",
    name: "Mono Brutalist",
    desc: "Σκληρές γωνίες, δυνατά περιγράμματα, acid accent.",
    swatch: ["#0a0a0a", "#d4ff3f", "#ffffff"],
    patch: {
      "theme.mode": "dark",
      "theme.bg": "#0a0a0a",
      "theme.surface": "#121212",
      "theme.accent": "#d4ff3f",
      "theme.accentDeep": "#5c7a00",
      "theme.accentSoft": "#eaffa3",
      "theme.borderColor": "#ffffff",
      "theme.borderOpacity": 22,
      "theme.cardRadius": 0,
      "theme.grain": false,
      "theme.glows": false,
      "theme.gridLines": true,
      "theme.fonts.display": "Archivo",
      "theme.fonts.body": "Archivo",
      "theme.fonts.headingWeight": 800,
      "theme.buttons.shape": "square",
      "theme.buttons.primaryBg": "#d4ff3f",
      "theme.buttons.primaryText": "#0a0a0a",
      "theme.buttons.secondaryStyle": "outline",
      "theme.icons.style": "outline",
    },
  },
];

export default TEMPLATES;
